#version 430
layout(local_size_x = 3) in;
layout( std430, binding=1 ) buffer Pos1
{
float a[]; 
};

layout( std430, binding=2 ) buffer Pos2
{
float b[]; 
};

layout( std430, binding=3 ) buffer Pos3
{
float c[]; 
};

layout( std430, binding=4 ) buffer VerteBuff
{
vec3 v[]; 
};
void main(){
uint gid = gl_GlobalInvocationID.x;
//c[gid] = a[gid] + b[gid];
vec3 d = vec3(0.0001, 0.002, 0.001);
v[gid] = v[gid] + d;
}